### PR TITLE
Migration to new React95 library

### LINKED ISSUE #2: Migrate from React95 to React95 😆
Migrate from [react95](https://github.com/arturbien/React95) to [react95](https://github.com/React95/React95).

Steps Involved: 
- Remove existing react95 library via yarn remove 
- Remove the AppBar component and replace it with a similar one from the new library

Reason: 
- We require the tree component available in the react95 library

### PR DESCRIPTION
**Pull request by Ishakikani9117**
fix #2 
@statebait please review this.

### CODE REVIEW

**Review by statebait — APPROVED** [review]
LGTM! Checked out the fork locally and its working correctly! Good Job!

**Comment by Tikam02** [comment]
give @Ishakikani9117  25 points

**Comment by Ishakikani9117** [comment]
@statebait @Tikam02  Can you please suggest tasks, like what we have to do next?

**Comment by statebait** [comment]
@Ishakikani9117 can you pick #3 ?

**Comment by Ishakikani9117** [comment]
> @Ishakikani9117 can you pick #3 ?

ok, I'll try.

**Pull request merged**
