### PR TITLE
Retrieved content repository

### LINKED ISSUE #3: Retrieve repository contents using GitHub API
Leverage the GitHub REST API to retrieve the AcadVault repository contents in a tree format (preferably recursive) so that they can be rendered into the UI.

Useful links -
* [GitHub API Docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/git#trees)
* [AcadVault Content Repo](https://github.com/Tikam02/AcadVault)

### PR DESCRIPTION
**Pull request by Ishakikani9117**
fix #3
@statebait please have a look at this.

### CODE REVIEW

**Review by statebait — APPROVED** [review]
LGTM

**Comment by Ishakikani9117** [comment]
@Tikam02 @statebait can you please share tasks that have to be done next?

**Comment by Tikam02** [comment]
give @Ishakikani9117 25 points

**Comment by Tikam02** [comment]
@Ishakikani9117 we will make issue for the next tasks.

**Pull request merged**
